// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Account struct {
	ID       int64     `json:"id"`
	Owner    string    `json:"owner"`
	Balance  int64     `json:"balance"`
	Currency string    `json:"currency"`
	CreateAt time.Time `json:"createAt"`
}

type Entries struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"accountID"`
	// can be +/-
	Amount   int64     `json:"amount"`
	CreateAt time.Time `json:"createAt"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"fromAccountID"`
	ToAccountID   int64 `json:"toAccountID"`
	// must be +
	Amount   int64     `json:"amount"`
	CreateAt time.Time `json:"createAt"`
}

type Users struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashedPassword"`
	FullName          string    `json:"fullName"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"passwordChangedAt"`
	CreateAt          time.Time `json:"createAt"`
}
